name: Publish Package

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: "https://registry.npmjs.org"

      - name: NPM Authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Increment Patch Version
        run: |
          npm version patch -m "Bump version to %s [skip ci]"
          git push
          git push --tags

      - name: Build Binaries
        run: |
          mkdir -p dist
          deno task compile

      - name: Publish
        run: |
          echo "Registry: $(npm config get registry)"
          echo "Auth Token Exists: $(test -n "$NPM_TOKEN" && echo "Yes" || echo "No")"
          npm publish --access restricted
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}